### ISSUE TITLE
Minimized Overlay doesnt show personal dps stat

### ISSUE THREAD

**Issue by altissia86** [Liquidize/FFXIV_PercentilePlugin#1]
When I'm not raiding I minimize kageorou to show only my personal stat and not others. But this percentile fork doesnt show anything

![capture](https://user-images.githubusercontent.com/43957601/47253342-6d065e80-d47b-11e8-8293-4b818c758d2b.PNG)
![capture2](https://user-images.githubusercontent.com/43957601/47253343-6d065e80-d47b-11e8-8de2-73f5a642e2e1.PNG)

PS : I know I need to add percentile column to show the plugin stat but after a little playing around and importing over my style I noticed the bug

**Comment by Liquidize** [comment]
Thanks for reporting this. Oddly it doesn't happen for me (see below for images) so I'm thinking perhaps it may be an issue with the custom styling? Are you modifying the CSS?

![](https://i.imgur.com/Ampqgfh.png)
![](https://i.imgur.com/2dBp6yo.png)

**Comment by altissia86** [comment]
i'm not. i was importing my kagerou one with the export tab and importing it in percentile. i'll try reseting tomorrow and modifying the style manually one by one.
