### ISSUE TITLE
Error on plugin load

### ISSUE THREAD

**Issue by xeno002** [Liquidize/FFXIV_PercentilePlugin#2]
Getting this error inizialisation. what am i doing wrong?
https://i.imgur.com/Q2HMPTv.png
https://i.imgur.com/piQSDOv.png

**Comment by Liquidize** [comment]
You need to place the DLL's in the folder with the "Advanced Combat Tracker.exe". ACT only looks for DLL's to load with plugins within its own folder. I have yet to make the plugin hotload its dependencies like the OverlayPlugin does.

**Comment by xeno002** [comment]
Thank you.
Putting only 'PercentilePlugin.Shared.dll' in the same folder as 'Advanced Combat Tracker.exe' fixed it.

I to keep the root folder clean. Hope the other 2 DLLs can stay in an extra folder.
