### ISSUE TITLE
Plugin Initialization Failed

### ISSUE THREAD

**Issue by Blazefyre0385** [Liquidize/FFXIV_PercentilePlugin#3]
I am continually getting this error when trying to enable the plugin in ACT. I have tried placing the DLLs in the same folder as Advanced Combat Tracker.exe but this error still occurs.

Thanks!

![image](https://user-images.githubusercontent.com/10395229/47408147-b8429a80-d723-11e8-9e11-894d67328302.png)

![image](https://user-images.githubusercontent.com/10395229/47408343-9a296a00-d724-11e8-9f77-c8755335f7c2.png)

**Comment by Liquidize** [comment]
Are the DLL's "Blocked" if you go into their properties make sure they are "Unblocked" by windows.

**Comment by Blazefyre0385** [comment]
Hey there! Thanks for your reply! :)

When I copied the file the first thing I actually did was unblock them. I'm pretty good about checking that these days!

![image](https://user-images.githubusercontent.com/10395229/47598963-f0d3b580-d969-11e8-9d4f-00ec83e04ab6.png)

**Comment by Liquidize** [comment]
Hmm, I am not quite sure why this is occurring then. I want to say try to reacquire the latest version but I'm not too sure if it will help. Do you have the latest .NET Framework? You need at least version 4.5.1 to run this. Try seeing if installing [this](https://www.microsoft.com/en-us/download/details.aspx?id=40779) fixes it + reacquiring it.

**Comment by Blazefyre0385** [comment]
I just grabbed your most recent version (v0.2.3) and it worked no problem! Thank you again! :)
