### ISSUE TITLE
Omega M/F and Omega Final do not work

### ISSUE THREAD

**Issue by fortris** [Liquidize/FFXIV_PercentilePlugin#6]
M/F just don't show anything, and Omega Final shows the Omega (o11s) rankings.

**Comment by Liquidize** [comment]
Could you please send me/upload a Network log file containing data o12/o12s? These are the files used to upload to FFLogs.

**Comment by fortris** [comment]
Smallest log I got on me rn is 40mb so I had to upload to discord 

https://cdn.discordapp.com/attachments/463118484050673684/507081361195270161/Network_20181023.2018.10.24-split-2018-10-24T04-21-51.064Z.log

**Comment by Liquidize** [comment]
Hi,

Thanks for this. I've gone ahead and fixed the issue(s). Final Omega should now use the proper data.
